# Generated by Django 5.2.10 on 2026-01-17 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bin_iin', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_number', models.CharField(max_length=100, unique=True, verbose_name='Р.О номер')),
                ('amount_without_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_with_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('ddl', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('comment', models.TextField(blank=True, null=True)),
                ('accountant_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'Отправлено'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('PAID', 'Оплачено'), ('CANCELLED', 'Отменено')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='main.customer')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_requests', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='main.supplier')),
            ],
        ),
    ]
