# Generated by Django 5.2.10 on 2026-01-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_purchaseitem_requestdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Ожидает рассмотрения'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('PAID', 'Оплачено'), ('CANCELLED', 'Отменено')], default='WAITING', max_length=20),
        ),
    ]
