# Generated by Django 5.2.10 on 2026-01-18 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_purchaserequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='accountant_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Accountant comment'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='amount_with_vat',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount with VAT'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='amount_without_vat',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount without VAT'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='main.customer', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='ddl',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='ro_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='R.O number'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='main.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5, verbose_name='VAT percent'),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='file',
            field=models.FileField(upload_to='purchase_requests/documents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('CONTRACT', 'Contract'), ('ACT', 'Act'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_details',
            field=models.TextField(blank=True, null=True, verbose_name='Bank details'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bin_iin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BIN/IIN'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
    ]
