# Generated by Django 5.2.10 on 2026-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customer_description_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for review'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20, verbose_name='Status'),
        ),
    ]
