# Generated by Django 5.2.10 on 2026-01-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Сотрудник'), ('MANAGER', 'Менеджер'), ('ACCOUNTANT', 'Бухгалтер'), ('ADMIN', 'Администратор')], default='EMPLOYEE', max_length=20, verbose_name='Role'),
        ),
    ]
